/*
FileMage Gateway

Testing AuditAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package filemagego

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	fm "github.com/elgranjero/filemagego"
)

func Test_filemagego_AuditAPIService(t *testing.T) {

	configuration := fm.NewConfiguration()
	apiClient := fm.NewAPIClient(configuration)

	t.Run("Test AuditAPIService ListLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuditAPI.ListLogs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
