/*
FileMage Gateway

FileMage Gateway provides a simple API to configure storage endpoints, users, and keys. Please note that all urls must end in a trailing slash, and the Content-Type header must be set to application/json.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package filemagego

import (
	"encoding/json"
)

// checks if the EndpointInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointInfo{}

// EndpointInfo struct for EndpointInfo
type EndpointInfo struct {
	// The ID of the endpoint.
	Id *int32 `json:"id,omitempty"`
	// Name of the endpoint.
	Name *string `json:"name,omitempty"`
}

// NewEndpointInfo instantiates a new EndpointInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointInfo() *EndpointInfo {
	this := EndpointInfo{}
	return &this
}

// NewEndpointInfoWithDefaults instantiates a new EndpointInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointInfoWithDefaults() *EndpointInfo {
	this := EndpointInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EndpointInfo) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointInfo) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EndpointInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EndpointInfo) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EndpointInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EndpointInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EndpointInfo) SetName(v string) {
	o.Name = &v
}

func (o EndpointInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableEndpointInfo struct {
	value *EndpointInfo
	isSet bool
}

func (v NullableEndpointInfo) Get() *EndpointInfo {
	return v.value
}

func (v *NullableEndpointInfo) Set(val *EndpointInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointInfo(val *EndpointInfo) *NullableEndpointInfo {
	return &NullableEndpointInfo{value: val, isSet: true}
}

func (v NullableEndpointInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


