/*
FileMage Gateway

FileMage Gateway provides a simple API to configure storage endpoints, users, and keys. Please note that all urls must end in a trailing slash, and the Content-Type header must be set to application/json.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package filemagego

import (
	"encoding/json"
)

// checks if the GCSEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GCSEndpoint{}

// GCSEndpoint struct for GCSEndpoint
type GCSEndpoint struct {
	// ID of returned endpoint.
	Id *int32 `json:"id,omitempty"`
	// Name of returned endpoint.
	Name *string `json:"name,omitempty"`
	Config *GCSEndpointConfig `json:"config,omitempty"`
}

// NewGCSEndpoint instantiates a new GCSEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGCSEndpoint() *GCSEndpoint {
	this := GCSEndpoint{}
	return &this
}

// NewGCSEndpointWithDefaults instantiates a new GCSEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCSEndpointWithDefaults() *GCSEndpoint {
	this := GCSEndpoint{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GCSEndpoint) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCSEndpoint) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GCSEndpoint) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GCSEndpoint) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GCSEndpoint) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCSEndpoint) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GCSEndpoint) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GCSEndpoint) SetName(v string) {
	o.Name = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GCSEndpoint) GetConfig() GCSEndpointConfig {
	if o == nil || IsNil(o.Config) {
		var ret GCSEndpointConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCSEndpoint) GetConfigOk() (*GCSEndpointConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GCSEndpoint) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given GCSEndpointConfig and assigns it to the Config field.
func (o *GCSEndpoint) SetConfig(v GCSEndpointConfig) {
	o.Config = &v
}

func (o GCSEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GCSEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableGCSEndpoint struct {
	value *GCSEndpoint
	isSet bool
}

func (v NullableGCSEndpoint) Get() *GCSEndpoint {
	return v.value
}

func (v *NullableGCSEndpoint) Set(val *GCSEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableGCSEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableGCSEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGCSEndpoint(val *GCSEndpoint) *NullableGCSEndpoint {
	return &NullableGCSEndpoint{value: val, isSet: true}
}

func (v NullableGCSEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGCSEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


