/*
FileMage Gateway

FileMage Gateway provides a simple API to configure storage endpoints, users, and keys. Please note that all urls must end in a trailing slash, and the Content-Type header must be set to application/json.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package filemagego

import (
	"encoding/json"
)

// checks if the GroupCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupCreated{}

// GroupCreated struct for GroupCreated
type GroupCreated struct {
	// The ID of the created group.
	Id *int32 `json:"id,omitempty"`
}

// NewGroupCreated instantiates a new GroupCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupCreated() *GroupCreated {
	this := GroupCreated{}
	return &this
}

// NewGroupCreatedWithDefaults instantiates a new GroupCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupCreatedWithDefaults() *GroupCreated {
	this := GroupCreated{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GroupCreated) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupCreated) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GroupCreated) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GroupCreated) SetId(v int32) {
	o.Id = &v
}

func (o GroupCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableGroupCreated struct {
	value *GroupCreated
	isSet bool
}

func (v NullableGroupCreated) Get() *GroupCreated {
	return v.value
}

func (v *NullableGroupCreated) Set(val *GroupCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupCreated(val *GroupCreated) *NullableGroupCreated {
	return &NullableGroupCreated{value: val, isSet: true}
}

func (v NullableGroupCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


